"""disponibilidad_ecografia

Revision ID: 04142878fc23
Revises: 7b804d34b182
Create Date: 2026-06-17 22:03:37.815954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04142878fc23'
down_revision: Union[str, Sequence[str], None] = '7b804d34b182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disponibilidades', sa.Column('es_ecografia', sa.Boolean(), nullable=True))
    op.alter_column('disponibilidades', 'especialidad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('disponibilidades_especialidad_id_fkey'), 'disponibilidades', type_='foreignkey')
    op.create_foreign_key(None, 'disponibilidades', 'especialidades', ['especialidad_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disponibilidades', type_='foreignkey')
    op.create_foreign_key(op.f('disponibilidades_especialidad_id_fkey'), 'disponibilidades', 'especialidades', ['especialidad_id'], ['id'], ondelete='CASCADE')
    op.alter_column('disponibilidades', 'especialidad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('disponibilidades', 'es_ecografia')
    # ### end Alembic commands ###
