"""turno_cobro_gasto_caja

Revision ID: 300ee65c1a9b
Revises: 94576ab2ce04
Create Date: 2026-06-28 20:49:08.639656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300ee65c1a9b'
down_revision: Union[str, Sequence[str], None] = '94576ab2ce04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_caja_id'), 'gastos_caja', ['id'], unique=False)
    op.add_column('turnos', sa.Column('orden', sa.Integer(), nullable=True))
    op.add_column('turnos', sa.Column('medio_pago', sa.String(length=20), nullable=True))
    op.add_column('turnos', sa.Column('monto_cobrado', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turnos', 'monto_cobrado')
    op.drop_column('turnos', 'medio_pago')
    op.drop_column('turnos', 'orden')
    op.drop_index(op.f('ix_gastos_caja_id'), table_name='gastos_caja')
    op.drop_table('gastos_caja')
    # ### end Alembic commands ###
