"""unificar_nombre_apellido_paciente

Revision ID: 68472a76685f
Revises: 300ee65c1a9b
Create Date: 2026-06-29 06:21:04.283050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68472a76685f'
down_revision: Union[str, Sequence[str], None] = '300ee65c1a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('pacientes', sa.Column('nombre_completo', sa.String(length=200), nullable=True))
    op.execute("UPDATE pacientes SET nombre_completo = apellido || ', ' || nombre")
    op.alter_column('pacientes', 'nombre_completo', nullable=False)
    op.drop_column('pacientes', 'apellido')
    op.drop_column('pacientes', 'nombre')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('pacientes', sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('pacientes', 'nombre_completo')
    # ### end Alembic commands ###
