"""drop_telefono_paciente

Revision ID: 94576ab2ce04
Revises: 5013150822a0
Create Date: 2026-06-28 00:13:05.435250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94576ab2ce04'
down_revision: Union[str, Sequence[str], None] = '5013150822a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'telefono')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('telefono', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
