"""precio_especialidad_tipos_ecografia

Revision ID: b1361cdfcd3b
Revises: 04142878fc23
Create Date: 2026-06-17 22:28:11.093210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1361cdfcd3b'
down_revision: Union[str, Sequence[str], None] = '04142878fc23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_ecografia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipos_ecografia_id'), 'tipos_ecografia', ['id'], unique=False)
    op.add_column('especialidades', sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('especialidades', 'precio')
    op.drop_index(op.f('ix_tipos_ecografia_id'), table_name='tipos_ecografia')
    op.drop_table('tipos_ecografia')
    # ### end Alembic commands ###
